language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build -x test"

before_deploy:
  - zip -r devbeginner-group *
  - mkdir -p deploy
  - mv devbeginner-group.zip deploy/devbeginner-group.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: deploy-devbeginner
    region: ap-northeast-2
    skip_cleanup: true
    local_dir: deploy
    acl: public_read
    wait-until-deployed: true
    on:
      repo: jojoldu/dev-beginner-group
      branch: master
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: deploy-devbeginner
    key: devbeginner-group.zip
    bundle_type: zip
    application: devbeginner-group
    deployment_group: devbeginner
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: jojoldu/dev-beginner-group
      branch: master

after_deploy:
  - echo "Performing after deploy procedures..."
  - /home/ec2-user/app/script/deploy.sh

notifications:
  email:
    recipients:
      - jojoldu@gmail.com
