language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build -x test"

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: deploy-travis-ci
    region: us-west-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: jojoldu/dev-beginner-group
      branch: master
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: deploy-travis-ci
    key: devbeginner-group.zip
    bundle_type: zip
    application: devbeginner-group
    deployment_group: devbeginner
    region: us-west-2
    wait-until-deployed: true
    on:
      repo: jojoldu/dev-beginner-group
      branch: master
after_deploy:
  - echo "Performing after deploy procedures..."
notifications:
  email:
    recipients:
      - jojoldu@gmail.com
