language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# 배포에 필요한 파일들만 deploy/devbeginner-group에 옮겨서 zip 파일로 만든다.
before_deploy:
  - mkdir -p web-archive && mkdir -p deploy
  - cp web-archive/build/libs/*.jar web-archive/
  - cp -r scripts/ web-archive/
  - cp appspec.yml web-archive/
  - zip -r deploy/web-archive.zip web-archive/

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: deploy-devbeginner
    region: ap-northeast-2
    skip_cleanup: true
    local_dir: deploy
    acl: public_read
    wait-until-deployed: true
    on:
      repo: jojoldu/dev-beginner-group
      branch: master
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: deploy-devbeginner
    key: web-archive.zip
    bundle_type: zip
    application: devbeginner-group
    deployment_group: devbeginner
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: jojoldu/dev-beginner-group
      branch: master

after_deploy:
  - echo "Code Deploy 배포 진행중입니다."

after_success:
- ./gradlew jacocoRootReport coveralls

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
