spring:
  profiles:
    active: local
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        default_batch_fetch_size: ${chunkSize:1000}
server:
  port: 8180
devbeginner:
  web:
    url: http://localhost:8080

cloud:
  aws:
    s3:
      bucket: devbeginner.com
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true
---
spring:
  profiles: local
  datasource:
    platform: h2
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MVCC=TRUE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: update
  devtools:
    livereload:
      enabled: true

---
spring.profiles: real
spring.profiles.include: real-db

devbeginner:
  web:
    url: https://www.devbeginner.com