spring:
  profiles:
    active: local
  jpa:
    open-in-view: false
server:
  port: 9080

devbeginner:
  static:
    enabled: true
  mail:
    enabled: true
  web:
    url: http://localhost:8080

---
spring:
  profiles: local

  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  devtools:
    livereload:
      enabled: true