spring:
  profiles:
    active: local
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        default_batch_fetch_size: ${chunkSize:1000}
server:
  port: 9080
devbeginner:
  static:
    enabled: true
  mail:
    enabled: true
  web:
    url: http://localhost:8080

---
spring:
  profiles: local
  datasource:
    platform: h2
    jdbcUrl: jdbc:h2:tcp://localhost:9092/mem:testdb;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  devtools:
    livereload:
      enabled: true

---
spring.profiles: set1
spring.profiles.include: real

server:
  port: 8081

---
spring.profiles: set2
spring.profiles.include: real

server:
  port: 8082


---
spring:
  profiles: real-app

devbeginner:
  static:
    enabled: true
  mail:
      enabled: true
  web:
      url: https://www.devbeginner.com
---
spring.profiles: set1
spring.profiles.include:
  - real-db
  - real-app

server:
  port: 9081
---
spring.profiles: set2
spring.profiles.include:
  - real-db
  - real-app

server:
  port: 9082