spring:
  profiles:
    active: local

server:
  port: 10040

devbeginner:
  static:
    enabled: true
  mail:
    enabled: true
---
spring:
  profiles: local

  jpa:
    database-platform: H2
    show-sql: true