spring:
  profiles:
    active: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        default_batch_fetch_size: ${chunkSize:1000}

  devtools:
    livereload:
      enabled: false
  mvc:
    favicon:
      enabled: true
server:
  port: 8080

logging.path: logs/dev-beginner-group-web/

devbeginner:
  web:
    url: http://localhost:8080

---
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    platform: h2
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MVCC=TRUE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  h2:
    console.enabled: true
    console.path: /h2-console #접속 URL -> jdbc:h2:mem:testdb, ID:sa, PW: (EMPTY)
    console.settings.trace: false
  devtools:
    livereload:
      enabled: true
handlebars.cache: false
---
spring:
  profiles: real-app

logging.path: /home/ec2-user/logs/dev-beginner-group-web/

devbeginner:
  web:
    url: https://www.devbeginner.com

---
spring.profiles: set1
spring.profiles.include:
  - real-db
  - real-app

server:
  port: 8081
---
spring.profiles: set2
spring.profiles.include:
  - real-db
  - real-app

server:
  port: 8082