spring:
  profiles:
    active: local

server:
  port: 10020

devbeginner:
  mail:
    enabled: true
  web:
    url: http://localhost:10020

---
spring:
  profiles: local

  jpa:
    database-platform: H2
    show-sql: true