spring:
  profiles:
    active: local
  thymeleaf:
    mode: LEGACYHTML5
server:
  port: 8080

devbeginner:
  mail:
    enabled: true
  web:
    url: http://localhost:8080


---
spring:
  profiles: local

  jpa:
    database-platform: H2
    show-sql: true
  pid:
    file: local-application.pid
  devtools:
    livereload:
      enabled: false
