spring:
  profiles: real-db
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    hikari:
      jdbc-url: {url}
      username: {username}
      password: {password}
      driver-class-name: org.mariadb.jdbc.Driver
      connectionTimeout: 10000
      idleTimeout: 600000      #10m
      maxLifetime: 600000     #10m
      maximumPoolSize: 5       # Pool 하나당 커넥션 수 (https://stackoverflow.com/a/27506460)