spring:
  profiles: real-db
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    hikari:
      jdbc-url: {url}
      username: {username}
      password: {password}
      driver-class-name: org.mariadb.jdbc.Driver
      idleTimeout: 600000      #10m
      maxLifetime: 1800000     #30m
      maximumPoolSize: 100